# Generated by Django 5.1 on 2025-11-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cafeteria', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='preferencias',
            field=models.TextField(blank=True),
        ),
    ]
